"""Add ISIN to assets and broker/exchange to transactions

Revision ID: 084230064650
Revises: c71ddac2a2bb
Create Date: 2026-05-06 22:12:19.285841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084230064650'
down_revision = 'c71ddac2a2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isin', sa.String(length=12), nullable=True))
        batch_op.create_index('idx_asset_isin', ['isin'], unique=False)
        batch_op.create_unique_constraint(None, ['isin'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broker', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exchange', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_index('idx_transactions_broker', ['broker'], unique=False)
        batch_op.create_index('idx_transactions_exchange', ['exchange'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_exchange')
        batch_op.drop_index('idx_transactions_broker')
        batch_op.drop_column('notes')
        batch_op.drop_column('exchange')
        batch_op.drop_column('broker')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_asset_isin')
        batch_op.drop_column('isin')

    # ### end Alembic commands ###
