"""Add dividends and total_return to closed_positions

Revision ID: 1e70cde6970a
Revises: e2fe2d3ee5a4
Create Date: 2026-05-11 16:53:47.858178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e70cde6970a'
down_revision = 'e2fe2d3ee5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_dividends', sa.Numeric(precision=20, scale=8), nullable=True))
        batch_op.add_column(sa.Column('total_return_percentage', sa.Numeric(precision=10, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.drop_column('total_return_percentage')
        batch_op.drop_column('total_dividends')

    # ### end Alembic commands ###
