"""Add tax_events table

Revision ID: 5e96246d5735
Revises: d42ac723db9e
Create Date: 2026-05-12 22:21:39.441492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e96246d5735'
down_revision = 'd42ac723db9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_events', schema=None) as batch_op:
        batch_op.alter_column('split_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_events', schema=None) as batch_op:
        batch_op.alter_column('split_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
