"""Add brokers exchanges asset_classes sectors currency_rates cash_flows

Revision ID: 684b8b4a0d73
Revises: 084230064650
Create Date: 2026-05-06 22:47:28.824810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684b8b4a0d73'
down_revision = '084230064650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_classes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['asset_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('brokers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('commission_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('currency_rates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency', 'rate_date', name='uix_currency_pair_date')
    )
    with op.batch_alter_table('currency_rates', schema=None) as batch_op:
        batch_op.create_index('idx_currency_rates_date', ['rate_date'], unique=False)
        batch_op.create_index('idx_currency_rates_pair', ['base_currency', 'target_currency'], unique=False)

    op.create_table('exchanges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sectors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gics_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cash_flows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('broker_id', sa.BigInteger(), nullable=True),
    sa.Column('flow_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('flow_date', sa.DateTime(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.create_index('idx_cash_flows_broker', ['broker_id'], unique=False)
        batch_op.create_index('idx_cash_flows_portfolio_date', ['portfolio_id', 'flow_date'], unique=False)
        batch_op.create_index('idx_cash_flows_type', ['flow_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_portfolio_id'), ['portfolio_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_class_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('sector_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('exchange_id', sa.BigInteger(), nullable=True))
        batch_op.create_index('idx_asset_class', ['asset_class_id'], unique=False)
        batch_op.create_index('idx_asset_sector', ['sector_id'], unique=False)
        batch_op.create_foreign_key(None, 'exchanges', ['exchange_id'], ['id'])
        batch_op.create_foreign_key(None, 'asset_classes', ['asset_class_id'], ['id'])
        batch_op.create_foreign_key(None, 'sectors', ['sector_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broker_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('exchange_id', sa.BigInteger(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_transactions_broker'))
        batch_op.create_index('idx_transactions_broker', ['broker_id'], unique=False)
        batch_op.drop_index(batch_op.f('idx_transactions_exchange'))
        batch_op.create_index('idx_transactions_exchange', ['exchange_id'], unique=False)
        batch_op.create_foreign_key(None, 'exchanges', ['exchange_id'], ['id'])
        batch_op.create_foreign_key(None, 'brokers', ['broker_id'], ['id'])
        batch_op.drop_column('broker')
        batch_op.drop_column('exchange')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('broker', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_transactions_exchange')
        batch_op.create_index(batch_op.f('idx_transactions_exchange'), ['exchange'], unique=False)
        batch_op.drop_index('idx_transactions_broker')
        batch_op.create_index(batch_op.f('idx_transactions_broker'), ['broker'], unique=False)
        batch_op.drop_column('exchange_id')
        batch_op.drop_column('broker_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_asset_sector')
        batch_op.drop_index('idx_asset_class')
        batch_op.drop_column('exchange_id')
        batch_op.drop_column('sector_id')
        batch_op.drop_column('asset_class_id')

    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_flows_portfolio_id'))
        batch_op.drop_index('idx_cash_flows_type')
        batch_op.drop_index('idx_cash_flows_portfolio_date')
        batch_op.drop_index('idx_cash_flows_broker')

    op.drop_table('cash_flows')
    op.drop_table('sectors')
    op.drop_table('exchanges')
    with op.batch_alter_table('currency_rates', schema=None) as batch_op:
        batch_op.drop_index('idx_currency_rates_pair')
        batch_op.drop_index('idx_currency_rates_date')

    op.drop_table('currency_rates')
    op.drop_table('brokers')
    op.drop_table('asset_classes')
    # ### end Alembic commands ###
