"""Add price_cache table for price caching

Revision ID: 975a8577ecef
Revises: 684b8b4a0d73
Create Date: 2026-05-08 22:56:29.757045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975a8577ecef'
down_revision = '684b8b4a0d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.create_index('idx_price_cache_last_update', ['last_update'], unique=False)
        batch_op.create_index('idx_price_cache_ticker', ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_cache_asset_id'), ['asset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_price_cache_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_cache_ticker'))
        batch_op.drop_index(batch_op.f('ix_price_cache_asset_id'))
        batch_op.drop_index('idx_price_cache_ticker')
        batch_op.drop_index('idx_price_cache_last_update')

    op.drop_table('price_cache')
    # ### end Alembic commands ###
