"""Initial migration

Revision ID: c71ddac2a2bb
Revises: 
Create Date: 2026-05-04 20:56:39.728966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c71ddac2a2bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('asset_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('assets_ticker_asset_type_key'), type_='unique')
        batch_op.create_unique_constraint('uix_ticker_type', ['ticker', 'asset_type'])
        batch_op.drop_column('isin')

    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historical_prices_asset_id_price_date_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_historical_prices_asset_id'), ['asset_id'], unique=False)
        batch_op.create_unique_constraint('uix_asset_date', ['asset_id', 'price_date'])
        batch_op.drop_constraint(batch_op.f('historical_prices_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'])

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_portfolios_user'))
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('portfolios_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_positions_portfolio'))
        batch_op.drop_constraint(batch_op.f('positions_portfolio_id_asset_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_positions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_unique_constraint('uix_portfolio_asset', ['portfolio_id', 'asset_id'])
        batch_op.drop_constraint(batch_op.f('positions_portfolio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'portfolios', ['portfolio_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('tx_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('tx_currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.alter_column('tx_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_transactions_asset'))
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_date'), ['tx_date'], unique=False)
        batch_op.drop_constraint(batch_op.f('transactions_portfolio_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('transactions_asset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'portfolios', ['portfolio_id'], ['id'])
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transactions_asset_id_fkey'), 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('transactions_portfolio_id_fkey'), 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_transactions_tx_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.create_index(batch_op.f('idx_transactions_asset'), ['asset_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('tx_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('tx_currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False)
        batch_op.alter_column('tx_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('positions_portfolio_id_fkey'), 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uix_portfolio_asset', type_='unique')
        batch_op.drop_index(batch_op.f('ix_positions_portfolio_id'))
        batch_op.create_unique_constraint(batch_op.f('positions_portfolio_id_asset_id_key'), ['portfolio_id', 'asset_id'])
        batch_op.create_index(batch_op.f('idx_positions_portfolio'), ['portfolio_id'], unique=False)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('portfolios_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.create_index(batch_op.f('idx_portfolios_user'), ['user_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historical_prices_asset_id_fkey'), 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uix_asset_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_historical_prices_asset_id'))
        batch_op.create_unique_constraint(batch_op.f('historical_prices_asset_id_price_date_key'), ['asset_id', 'price_date'])

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isin', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uix_ticker_type', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('assets_ticker_asset_type_key'), ['ticker', 'asset_type'])
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False)
        batch_op.alter_column('asset_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('ticker',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
