"""Add tax_events and split_events tables

Revision ID: e106e0e0871c
Revises: ed7b94ae7bce
Create Date: 2026-05-12 17:26:09.585993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e106e0e0871c'
down_revision = 'ed7b94ae7bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('split_type', sa.String(length=10), nullable=False),
    sa.Column('old_quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('new_quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('split_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('split_events', schema=None) as batch_op:
        batch_op.create_index('idx_split_asset', ['asset_id'], unique=False)
        batch_op.create_index('idx_split_date', ['split_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_split_events_asset_id'), ['asset_id'], unique=False)

    op.create_table('tax_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('tax_type', sa.String(length=30), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_date', sa.DateTime(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_events', schema=None) as batch_op:
        batch_op.create_index('idx_tax_asset', ['asset_id'], unique=False)
        batch_op.create_index('idx_tax_date', ['tax_date'], unique=False)
        batch_op.create_index('idx_tax_portfolio', ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_events_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_events_portfolio_id'))
        batch_op.drop_index('idx_tax_portfolio')
        batch_op.drop_index('idx_tax_date')
        batch_op.drop_index('idx_tax_asset')

    op.drop_table('tax_events')
    with op.batch_alter_table('split_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_split_events_asset_id'))
        batch_op.drop_index('idx_split_date')
        batch_op.drop_index('idx_split_asset')

    op.drop_table('split_events')
    # ### end Alembic commands ###
