"""Add closed_positions table

Revision ID: e2fe2d3ee5a4
Revises: 975a8577ecef
Create Date: 2026-05-08 23:34:17.363306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fe2d3ee5a4'
down_revision = '975a8577ecef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_buy_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_sold_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_sell_revenue', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('return_percentage', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('first_buy_date', sa.DateTime(), nullable=False),
    sa.Column('last_sell_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.create_index('idx_closed_portfolio_asset', ['portfolio_id', 'asset_id'], unique=False)
        batch_op.create_index('idx_closed_sell_date', ['last_sell_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_positions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_positions_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closed_positions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_closed_positions_asset_id'))
        batch_op.drop_index('idx_closed_sell_date')
        batch_op.drop_index('idx_closed_portfolio_asset')

    op.drop_table('closed_positions')
    # ### end Alembic commands ###
