"""Add bond fields to assets

Revision ID: f988a97a4e8e
Revises: 1e70cde6970a
Create Date: 2026-05-11 17:07:10.232949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f988a97a4e8e'
down_revision = '1e70cde6970a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_value', sa.Numeric(precision=20, scale=2), nullable=True))
        batch_op.add_column(sa.Column('coupon_rate', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('maturity_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('maturity_date')
        batch_op.drop_column('coupon_rate')
        batch_op.drop_column('face_value')

    # ### end Alembic commands ###
